// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4CaryIybprDY0p8LcVjJb5mbTJajvOUI',
    appId: '1:61594424341:web:d31a8e9d04797a2f81ea1c',
    messagingSenderId: '61594424341',
    projectId: 'mobile-application-proje-6ad9f',
    authDomain: 'mobile-application-proje-6ad9f.firebaseapp.com',
    storageBucket: 'mobile-application-proje-6ad9f.appspot.com',
    measurementId: 'G-PVY40JV7R2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArh-piE4aIw1SY1JX_-cHOu5wqEPJUdXE',
    appId: '1:61594424341:android:501cc0cc13640dbd81ea1c',
    messagingSenderId: '61594424341',
    projectId: 'mobile-application-proje-6ad9f',
    storageBucket: 'mobile-application-proje-6ad9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJbGOEapyY8I4-uYOeQSP9Y4P30v_VHT0',
    appId: '1:61594424341:ios:21926cf48afc46cd81ea1c',
    messagingSenderId: '61594424341',
    projectId: 'mobile-application-proje-6ad9f',
    storageBucket: 'mobile-application-proje-6ad9f.appspot.com',
    iosBundleId: 'com.example.airyshare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJbGOEapyY8I4-uYOeQSP9Y4P30v_VHT0',
    appId: '1:61594424341:ios:21926cf48afc46cd81ea1c',
    messagingSenderId: '61594424341',
    projectId: 'mobile-application-proje-6ad9f',
    storageBucket: 'mobile-application-proje-6ad9f.appspot.com',
    iosBundleId: 'com.example.airyshare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4CaryIybprDY0p8LcVjJb5mbTJajvOUI',
    appId: '1:61594424341:web:bbe84464cd3e594081ea1c',
    messagingSenderId: '61594424341',
    projectId: 'mobile-application-proje-6ad9f',
    authDomain: 'mobile-application-proje-6ad9f.firebaseapp.com',
    storageBucket: 'mobile-application-proje-6ad9f.appspot.com',
    measurementId: 'G-35LVMBZVHN',
  );
}
